### PR TITLE
Win warn clean

### PR DESCRIPTION
**Pull request by lukasz-m-maciejewski**
Enabled the following warnings for default target + Werror + warning cleanup
* -Wswitch-enum
* -Wmissing-declarations
* -Wshadow
* -Wconversion
* -Wfloat-equal
* -Wunreachable-code

---
This change is [Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/papuc_exercises/31)

### CODE REVIEW

**Comment by Abergard** [comment]
Good job.

---

Reviewed 27 of 27 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[ib/ch04/ch_04_05.cpp, line 14 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/31#-KX0AkP2jvHdhc_6hrYt:-KX0AkP3H9C71FF3TZjE:buqv834) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/dc67763a5624e514fa5b4e24058975d662bc503a/ib/ch04/ch_04_05.cpp#L14)):*
> ```cpp
>     case '*': return arg1 * arg2; break;
>     case ':':
>         if (std::fabs(arg2) < epsilon)
> ```

Please take into consideration to use variable from standard (i.e. std::numeric_limits<T>::epsilon())

---

*[ib/ch04/ch_04_05.hpp, line 18 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/31#-KX0B6ML_ptRL8u1DYdm:-KX0B6MMBx-VSPn22wRk:b-x1tzp) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/dc67763a5624e514fa5b4e24058975d662bc503a/ib/ch04/ch_04_05.hpp#L18)):*
> ```cpp
> private:
>     char action;
>     constexpr static double epsilon{0.00001};
> ```

It is unnecessary since we have std::numeric_limits<T>::epsilon() in c++ standard

---

*[ib/ch05/SquareEquation.cpp, line 11 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/31#-KX0BJC9St52ilaChZPS:-KX0BJC9St52ilaChZPT:b-3fwusq) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/dc67763a5624e514fa5b4e24058975d662bc503a/ib/ch05/SquareEquation.cpp#L11)):*
> ```cpp
> namespace
> {
> constexpr double epsilon{0.00001};
> ```

Next place where epsilon declaration is unnecessary

---

*[lm/ch04/RPS.hpp, line 73 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/31#-KX0Bmj-VCDG3jPsKjPD:-KX0Bmj-VCDG3jPsKjPE:b-uo9r0a) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/dc67763a5624e514fa5b4e24058975d662bc503a/lm/ch04/RPS.hpp#L73)):*
> MatchResult(Move lhsMove, Move rhsMove);
> 
> MatchResult(Move lhsMove, Move rhsMove)
< {

Why did you add function declaration. The definition of getMatchResult isn't definition and declaration in the same time here?

---

*[lm/ch06/Evaluator.hpp, line 21 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/31#-KX0CkkbD6ADCEv2HmV2:-KX0CkkcC84KPJ0JI0NQ:b-9ejeyi) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/dc67763a5624e514fa5b4e24058975d662bc503a/lm/ch06/Evaluator.hpp#L21)):*
> ```cpp
>     std::unique_ptr<TokenStream> tsVal;
>     TokenStream& ts;
>     constexpr static double epsilon{0.00001};
> ```

Own declaration of epsilon again. Look at other comments.

---

*[lm/ch06/Token.cpp, line 41 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/31#-KX0D5Fp6L_t9A8iRTt7:-KX0D5Fp6L_t9A8iRTt8:b4871zb) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/dc67763a5624e514fa5b4e24058975d662bc503a/lm/ch06/Token.cpp#L41)):*
> ```cpp
> bool operator==(const Token& lhs, const Token& rhs)
> {
>     constexpr double epsilon{0.00001};
> ```

epsilon... look at other comments

---

*[mb/ch06/Calculator.hpp, line 18 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/31#-KX0DbXIghwAff8fdi4g:-KX0DbXIghwAff8fdi4h:b-3fy6or) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/dc67763a5624e514fa5b4e24058975d662bc503a/mb/ch06/Calculator.hpp#L18)):*
> ```cpp
> private:
>     ITokenStream& tokenStream;
>     constexpr static double epsilon{0.00001};
> ```

eplsilon...look at other comments

---

*[mb/ch06/Token.cpp, line 14 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/31#-KX0DgYkaQdLTPeT_1wa:-KX0DgYl12vIXlneKhbl:b-svjw9x) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/dc67763a5624e514fa5b4e24058975d662bc503a/mb/ch06/Token.cpp#L14)):*
> ```cpp
> bool operator==(const Token& left, const Token& right)
> {
>     constexpr double epsilon{0.00001};
> ```

use std::numeric_limits::epsilon

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/31#-:-KX0DmLnnwrfLcDqy_m7:b-ul7oq9)*

**Comment by Abergard** [comment]
Reviewed 15 of 15 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[CMakeLists.txt, line 46 at r2](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/31#-KX2VIEhCFX-CZjUfstV:-KX2VIEiIP-wMZ_mSLTa:bk7khos) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/2b6f9cac491628f98d7dd0a7bad223598ceec8f9/CMakeLists.txt#L46)):*
> ```CMake
>  -Wno-language-extension-token -Wno-used-but-marked-unused\
>  -Wno-shift-sign-overflow -Wno-deprecated\
>  -Wno-weak-vtables -Wno-sign-conversion -Wno-padded -Wno-covered-switch-default")
> ```

Why did you disabled warning for covered-switch-default ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/31)*

**Comment by lukasz-m-maciejewski** [comment]
Thanks :-)

---

Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[CMakeLists.txt, line 46 at r2](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/31#-KX2VIEhCFX-CZjUfstV:-KX5aRRRDrknIkRMAuAv:bu9r276) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/2b6f9cac491628f98d7dd0a7bad223598ceec8f9/CMakeLists.txt#L46)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary>
> Why did you disabled warning for covered-switch-default ?
</details>
It is sometimes useful, but probably can always be avoided. Let's discuss this with everyone.

---

*[ib/ch04/ch_04_05.cpp, line 14 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/31#-KX0AkP2jvHdhc_6hrYt:-KX5am5YU9GXjRfNodug:b-896fix) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/dc67763a5624e514fa5b4e24058975d662bc503a/ib/ch04/ch_04_05.cpp#L14)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary>
> Please take into consideration to use variable from standard (i.e. std::numeric_limits<T>::epsilon())
</details>
Done.

---

*[ib/ch04/ch_04_05.hpp, line 18 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/31#-KX0B6ML_ptRL8u1DYdm:-KX5anU5Y6x__JKwRyP_:b-896fix) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/dc67763a5624e514fa5b4e24058975d662bc503a/ib/ch04/ch_04_05.hpp#L18)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary>
> It is unnecessary since we have std::numeric_limits<T>::epsilon() in c++ standard
</details>
Done.

---

*[ib/ch05/SquareEquation.cpp, line 11 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/31#-KX0BJC9St52ilaChZPS:-KX5aoLgl-69Qgrz49cF:b-896fix) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/dc67763a5624e514fa5b4e24058975d662bc503a/ib/ch05/SquareEquation.cpp#L11)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary>
> Next place where epsilon declaration is unnecessary
</details>
Done.

---

*[lm/ch04/RPS.hpp, line 73 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/31#-KX0Bmj-VCDG3jPsKjPD:-KX0RlYAKXLwNpmBdZwU:bx92f27) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/dc67763a5624e514fa5b4e24058975d662bc503a/lm/ch04/RPS.hpp#L73)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary>
> > MatchResult(Move lhsMove, Move rhsMove);
> > 
> > MatchResult(Move lhsMove, Move rhsMove)
> < {
> 
> Why did you add function declaration. The definition of getMatchResult isn't definition and declaration in the same time here?
> 
> 
</details>
I find this weird as well, but Clang had a warning about this function. Apparently it dislikes previously undeclared methods. It seems wiser to disable this warning instead, but this was more fun. ;-)

---

*[lm/ch06/Token.cpp, line 41 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/31#-KX0D5Fp6L_t9A8iRTt7:-KX5aqOb7kqCqoYd1ikw:b-896fix) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/dc67763a5624e514fa5b4e24058975d662bc503a/lm/ch06/Token.cpp#L41)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary>
> epsilon... look at other comments
</details>
Done.

---

*[mb/ch06/Token.cpp, line 14 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/31#-KX0DgYkaQdLTPeT_1wa:-KX5arIX_Hymww4bilbE:b-896fix) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/dc67763a5624e514fa5b4e24058975d662bc503a/mb/ch06/Token.cpp#L14)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary>
> use std::numeric_limits::epsilon
</details>
Done.

---

*[lm/ch06/Evaluator.hpp, line 21 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/31#-KX0CkkbD6ADCEv2HmV2:-KX5asHipbd3lczhjFtz:b-896fix) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/dc67763a5624e514fa5b4e24058975d662bc503a/lm/ch06/Evaluator.hpp#L21)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary>
> Own declaration of epsilon again. Look at other comments.
</details>
Done.

---

*[mb/ch06/Calculator.hpp, line 18 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/31#-KX0DbXIghwAff8fdi4g:-KX5atGpW9A1Xoyd4Q1Y:b-896fix) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/dc67763a5624e514fa5b4e24058975d662bc503a/mb/ch06/Calculator.hpp#L18)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary>
> eplsilon...look at other comments
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/31#-:-KX5avmELL5SllzxhfBl:b-7z4718)*

**Comment by lukasz-m-maciejewski** [comment]
Please verify the open issues and comment or close them - they're currently blocking the merge

---

Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/31#-:-KX80X0D6i-InqO-e2Yj:b-ksw7t5)*

**Comment by Abergard** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/31)*

**Pull request merged**
