### PR TITLE
Adding Leds **....**

### PR DESCRIPTION
**Pull request by Feldmarszalekduda**
This change is [Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/papuc_exercises/39)

### CODE REVIEW

**Comment by kn65op** [comment]
Reviewed 16 of 17 files at r2.
Review status: all files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[mb/Leds/InstructionConverter.cpp, line 52 at r2](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/39#-KYVO-mZmAm-XRsYASoI:-KYVO-mZmAm-XRsYASoJ:bs67ujm) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/b8d56162046654e3c41bed9ed65faa99b2c6d547/mb/Leds/InstructionConverter.cpp#L52)):*
> ```cpp
>                 break;
>             }
>             default: break;
> ```

You don't need default when it doing nothing

---

*[mb/Leds/InstructionConverter.cpp, line 59 at r2](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/39#-KYVO9tM_7vsAzCiNQ6b:-KYVO9tM_7vsAzCiNQ6c:bdk8o9k) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/b8d56162046654e3c41bed9ed65faa99b2c6d547/mb/Leds/InstructionConverter.cpp#L59)):*
>     LedValue = (LedValue >= 128) ? (static_cast<std::uint8_t>(LedValue << 1) +1) :
>                                            (static_cast<unsigned>(LedValue) << 1);
Why do you cast one option into uint8_t and second into unsigned? 
It would be better to keep it consistent.


Also for readability the part before '?' would be nice to have in function:
LedValue = isMoreSignificantBitSet() ? ... : ...; or similar

---

*[mb/Leds/InstructionConverter.cpp, line 65 at r2](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/39#-KYVOe3qSWOpwguYkhES:-KYVOe3qSWOpwguYkhET:b-ya81ng) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/b8d56162046654e3c41bed9ed65faa99b2c6d547/mb/Leds/InstructionConverter.cpp#L65)):*
> ```cpp
> void InstructionConverter::moveBitsToRight()
> {
>     LedValue = (LedValue % 2) ? (static_cast<std::uint8_t>(LedValue >> 1) + 128) :
> ```

Same as above

---

*[mb/Leds/InstructionParser.cpp, line 53 at r2](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/39#-KYVQTKmzWmCuP7nER4B:-KYVQTKngKuDaQnhFbYY:b-px97z3) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/b8d56162046654e3c41bed9ed65faa99b2c6d547/mb/Leds/InstructionParser.cpp#L53)):*
> ```cpp
>                 setLabel(instructionFromLine);
>                 setEndLabelRegex();
>                 isInstructionInLabel = true;
> ```

I understand that you assume that there can be only one label in whole program. Requirements does not specify how much labels can be created, so it may fail some valid programs.

---

*[mb/Leds/InstructionParser.cpp, line 76 at r2](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/39#-KYVQs-Ufsv8MfAKtCxP:-KYVQs-Ufsv8MfAKtCxQ:bcgw6jc) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/b8d56162046654e3c41bed9ed65faa99b2c6d547/mb/Leds/InstructionParser.cpp#L76)):*
> ```cpp
> }
> 
> std::string InstructionParser::removeWhitespacesFromEnds(const std::string& line)
> ```

There is boost function for doing it.
http://www.boost.org/doc/libs/1_60_0/doc/html/string_algo/usage.html#idm45555128646416

---

*[mb/Leds/InstructionParser.cpp, line 92 at r2](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/39#-KYVR04mj0OjFMl9RtGw:-KYVR04mj0OjFMl9RtGx:b-zbmgai) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/b8d56162046654e3c41bed9ed65faa99b2c6d547/mb/Leds/InstructionParser.cpp#L92)):*
> ```cpp
> {
>     const std::string stringValue = line.substr( ldbPrefix.length() );
>     return static_cast<unsigned>(std::stoi(stringValue));
> ```

this line is repeated twice, would be nice to have common function to doing stoui.

---

*[mb/Leds/InstructionParser.cpp, line 112 at r2](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/39#-KYVR_3oxJlwgr7W1a2P:-KYVR_3oxJlwgr7W1a2Q:b-iuu9p4) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/b8d56162046654e3c41bed9ed65faa99b2c6d547/mb/Leds/InstructionParser.cpp#L112)):*
> ```cpp
>         if(instruction == ldbPrefix)
>         {
>             flatInstructions.insert(flatInstructions.end(),
> ```

Consider returning flatInstructions instead of saving in member

---

*[mb/Leds/LedCommon.cpp, line 43 at r2](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/39#-KYVRyjcA74J95dTDQYw:-KYVRyjcA74J95dTDQYx:b-4h7xtl) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/b8d56162046654e3c41bed9ed65faa99b2c6d547/mb/Leds/LedCommon.cpp#L43)):*
> ```cpp
>             fileAsVector.push_back(line);
>         }
>         inputFile.close();
> ```

You don't need to close by hand, it will be done in destructor.

---

*[mb/Leds/LedCommon.hpp, line 26 at r2](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/39#-KYVSYuWcy_xlb-DPYmj:-KYVSYuWcy_xlb-DPYmk:bven9ys) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/b8d56162046654e3c41bed9ed65faa99b2c6d547/mb/Leds/LedCommon.hpp#L26)):*
> ```cpp
> };
> 
> static std::map<std::string, std::regex> InstructionRegexp {
> ```

It's better to define thing like this in source file. When changed (and such things are likely to be changed) you will need to recompile only one file. When you have it in header then you will need recompilation of more files.

---

*[mb/Leds/main.cpp, line 13 at r2](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/39#-KYVT8RH8BM-eQhbI6ht:-KYVT8RH8BM-eQhbI6hu:b-yxlvmt) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/b8d56162046654e3c41bed9ed65faa99b2c6d547/mb/Leds/main.cpp#L13)):*
> ```cpp
> {
> 
>     std::string inputFile = "LedSequence.txt";
> ```

It's make integtation test hard. Standard behaviour is to read from stdin and if you have file with data you can just run ./bin < file.txt

---

*[mb/Leds/main.cpp, line 16 at r2](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/39#-KYVTNiM9VCnxTFNv8ws:-KYVTNiM9VCnxTFNv8wt:b-lcixio) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/b8d56162046654e3c41bed9ed65faa99b2c6d547/mb/Leds/main.cpp#L16)):*
> ```cpp
>     const auto vectorizedFile = convertFileToStringVector("LedSequence.txt");
> 
>     InstructionParser parser{};
> ```

{} is redundant

---

*[mb/Leds/main.cpp, line 18 at r2](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/39#-KYVTPp_4O_POvV9bxYO:-KYVTPp_4O_POvV9bxYP:b-lcixio) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/b8d56162046654e3c41bed9ed65faa99b2c6d547/mb/Leds/main.cpp#L18)):*
> ```cpp
>     InstructionParser parser{};
>     const auto flatInstructions = parser.getFlatInstructions(vectorizedFile);
>     InstructionConverter converter{};
> ```

{} is redundant

---

*[mb/Leds/main.cpp, line 21 at r2](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/39#-KYVTSERA2ZqFlLv-frU:-KYVTSERA2ZqFlLv-frV:b-lcixio) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/b8d56162046654e3c41bed9ed65faa99b2c6d547/mb/Leds/main.cpp#L21)):*
> ```cpp
>     converter.instructionsToLedsValues(flatInstructions);
>     std::vector<unsigned> ledBlinksValues = converter.getLedsValues();
>     LedBlinker blinker{};
> ```

{} is redundant

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/39)*

**Comment by Abergard** [comment]
Reviewed 16 of 17 files at r2.
Review status: all files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/39)*

**Comment by Feldmarszalekduda** [comment]
Review status: all files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[mb/Leds/InstructionConverter.cpp, line 52 at r2](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/39#-KYVO-mZmAm-XRsYASoI:-KYsyo-a2rCd_jdfMkna:b-896fix) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/b8d56162046654e3c41bed9ed65faa99b2c6d547/mb/Leds/InstructionConverter.cpp#L52)):*
<details><summary><i>Previously, kn65op (Tomasz Drzewiecki) wrote…</i></summary><blockquote>

You don't need default when it doing nothing
</blockquote></details>

Done.

---

*[mb/Leds/InstructionConverter.cpp, line 59 at r2](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/39#-KYVO9tM_7vsAzCiNQ6b:-KYtXxN0MErLxtMyr5lK:b-896fix) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/b8d56162046654e3c41bed9ed65faa99b2c6d547/mb/Leds/InstructionConverter.cpp#L59)):*
<details><summary><i>Previously, kn65op (Tomasz Drzewiecki) wrote…</i></summary><blockquote>

>     LedValue = (LedValue >= 128) ? (static_cast<std::uint8_t>(LedValue << 1) +1) :
>                                            (static_cast<unsigned>(LedValue) << 1);
Why do you cast one option into uint8_t and second into unsigned? 
It would be better to keep it consistent.


Also for readability the part before '?' would be nice to have in function:
LedValue = isMoreSignificantBitSet() ? ... : ...; or similar
</blockquote></details>

Done.

---

*[mb/Leds/InstructionConverter.cpp, line 65 at r2](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/39#-KYVOe3qSWOpwguYkhES:-KYtXz2Y5QnX3hAF3glp:b-896fix) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/b8d56162046654e3c41bed9ed65faa99b2c6d547/mb/Leds/InstructionConverter.cpp#L65)):*
<details><summary><i>Previously, kn65op (Tomasz Drzewiecki) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Done.

---

*[mb/Leds/InstructionParser.cpp, line 53 at r2](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/39#-KYVQTKmzWmCuP7nER4B:-KYsysWwhAg2CxMSsJn6:b-ga4hiu) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/b8d56162046654e3c41bed9ed65faa99b2c6d547/mb/Leds/InstructionParser.cpp#L53)):*
<details><summary><i>Previously, kn65op (Tomasz Drzewiecki) wrote…</i></summary><blockquote>

I understand that you assume that there can be only one label in whole program. Requirements does not specify how much labels can be created, so it may fail some valid programs.
</blockquote></details>

Yes, I assumed that there could be only one label.

---

*[mb/Leds/InstructionParser.cpp, line 76 at r2](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/39#-KYVQs-Ufsv8MfAKtCxP:-KYtEv7S7fc7V4r9xdZ-:b-896fix) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/b8d56162046654e3c41bed9ed65faa99b2c6d547/mb/Leds/InstructionParser.cpp#L76)):*
<details><summary><i>Previously, kn65op (Tomasz Drzewiecki) wrote…</i></summary><blockquote>

There is boost function for doing it.
http://www.boost.org/doc/libs/1_60_0/doc/html/string_algo/usage.html#idm45555128646416
</blockquote></details>

Done.

---

*[mb/Leds/InstructionParser.cpp, line 92 at r2](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/39#-KYVR04mj0OjFMl9RtGw:-KYt_7HiC_L_aUdEra5I:b-896fix) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/b8d56162046654e3c41bed9ed65faa99b2c6d547/mb/Leds/InstructionParser.cpp#L92)):*
<details><summary><i>Previously, kn65op (Tomasz Drzewiecki) wrote…</i></summary><blockquote>

this line is repeated twice, would be nice to have common function to doing stoui.
</blockquote></details>

Done.

---

*[mb/Leds/InstructionParser.cpp, line 112 at r2](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/39#-KYVR_3oxJlwgr7W1a2P:-KYtfxn0VGUzkahTYEkq:b-896fix) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/b8d56162046654e3c41bed9ed65faa99b2c6d547/mb/Leds/InstructionParser.cpp#L112)):*
<details><summary><i>Previously, kn65op (Tomasz Drzewiecki) wrote…</i></summary><blockquote>

Consider returning flatInstructions instead of saving in member
</blockquote></details>

Done.

---

*[mb/Leds/LedCommon.cpp, line 43 at r2](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/39#-KYVRyjcA74J95dTDQYw:-KYt0Cm-m17KOt_15Pru:b-896fix) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/b8d56162046654e3c41bed9ed65faa99b2c6d547/mb/Leds/LedCommon.cpp#L43)):*
<details><summary><i>Previously, kn65op (Tomasz Drzewiecki) wrote…</i></summary><blockquote>

You don't need to close by hand, it will be done in destructor.
</blockquote></details>

Done.

---

*[mb/Leds/LedCommon.hpp, line 26 at r2](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/39#-KYVSYuWcy_xlb-DPYmj:-KYtYXEMVivtpHlB2Pj8:b-896fix) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/b8d56162046654e3c41bed9ed65faa99b2c6d547/mb/Leds/LedCommon.hpp#L26)):*
<details><summary><i>Previously, kn65op (Tomasz Drzewiecki) wrote…</i></summary><blockquote>

It's better to define thing like this in source file. When changed (and such things are likely to be changed) you will need to recompile only one file. When you have it in header then you will need recompilation of more files.
</blockquote></details>

Done.

---

*[mb/Leds/main.cpp, line 16 at r2](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/39#-KYVTNiM9VCnxTFNv8ws:-KYtgBZbg1G07c6hEXof:b-896fix) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/b8d56162046654e3c41bed9ed65faa99b2c6d547/mb/Leds/main.cpp#L16)):*
<details><summary><i>Previously, kn65op (Tomasz Drzewiecki) wrote…</i></summary><blockquote>

{} is redundant
</blockquote></details>

Done.

---

*[mb/Leds/main.cpp, line 18 at r2](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/39#-KYVTPp_4O_POvV9bxYO:-KYtgC2tTodEHj-3tfWB:b-896fix) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/b8d56162046654e3c41bed9ed65faa99b2c6d547/mb/Leds/main.cpp#L18)):*
<details><summary><i>Previously, kn65op (Tomasz Drzewiecki) wrote…</i></summary><blockquote>

{} is redundant
</blockquote></details>

Done.

---

*[mb/Leds/main.cpp, line 21 at r2](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/39#-KYVTSERA2ZqFlLv-frU:-KYtgF0RIQVqwYkMD4PP:b-896fix) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/b8d56162046654e3c41bed9ed65faa99b2c6d547/mb/Leds/main.cpp#L21)):*
<details><summary><i>Previously, kn65op (Tomasz Drzewiecki) wrote…</i></summary><blockquote>

{} is redundant
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/39)*

**Comment by Abergard** [comment]
Reviewed 7 of 8 files at r3.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/39)*

**Comment by lukasz-m-maciejewski** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 13 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/39#-:-KZ2d5uh4VGPPdaaXAUi:bg7igk9)*

**Comment by Feldmarszalekduda** [comment]
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[mb/Leds/InstructionParser.cpp, line 53 at r2](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/39#-KYVQTKmzWmCuP7nER4B:-KZSHrPRvlJ9m4MLf36w:b-tt37gp) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/b8d56162046654e3c41bed9ed65faa99b2c6d547/mb/Leds/InstructionParser.cpp#L53)):*
<details><summary><i>Previously, Feldmarszalekduda wrote…</i></summary><blockquote>

Yes, I assumed that there could be only one label.
</blockquote></details>

This will be changed in version 2.0 

---

*[mb/Leds/main.cpp, line 13 at r2](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/39#-KYVT8RH8BM-eQhbI6ht:-KZSHdyEWE40PFFtGchH:b-tt37gp) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/b8d56162046654e3c41bed9ed65faa99b2c6d547/mb/Leds/main.cpp#L13)):*
<details><summary><i>Previously, kn65op (Tomasz Drzewiecki) wrote…</i></summary><blockquote>

It's make integtation test hard. Standard behaviour is to read from stdin and if you have file with data you can just run ./bin < file.txt
</blockquote></details>

This will be changed in version 2.0 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/39)*

**Pull request merged**
