### PR TITLE
Lm fmtgp

### PR DESCRIPTION
**Pull request by lukasz-m-maciejewski**
This change is [Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/papuc_exercises/70)

### CODE REVIEW

**Comment by Abergard** [comment]
Reviewed 2 of 11 files at r1.
Review status: 2 of 11 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[CMakeLists.txt, line 11 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/70#-KjickjV7H0-xLyX0KLz:-KjickjV7H0-xLyX0KM-:b-loz70q) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/03a453aeddd0a66a063451ab1d9408dcd9924c99/CMakeLists.txt#L11)):*
> ```CMake
> add_subdirectory(external/googletest)
> set(BENCHMARK_ENABLE_TESTING OFF CACHE BOOL "Do not run external tests")
> add_subdirectory(external/benchmark)
> ```

This line need to be below include platforms/Windows.cmake.
As default windows will try to build with shared library, however we are using static library.

---

*[lm/fmtgp/CMakeLists.txt, line 22 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/70#-KjidTkEYviQ3ZdDurHn:-KjidTkEYviQ3ZdDurHo:b-2xtpbb) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/03a453aeddd0a66a063451ab1d9408dcd9924c99/lm/fmtgp/CMakeLists.txt#L22)):*
> ```CMake
>   Ch12.bench.cpp)
> 
> target_link_libraries(lm-fmtgp-bench lm-fmtgp-lib benchmark pthread)
> ```

For windows compilation you need to delete pthread from target library,  windows doesn't have it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/70)*

**Comment by Abergard** [comment]
Reviewed 4 of 11 files at r1, 16 of 19 files at r3, 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[lm/CMakeLists.txt, line 26 at r4](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/70#-L3x2eERt3Ng2_PEGl0N:-L3x2eERt3Ng2_PEGl0O:b-b79ox5) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/1202bf4671a3bb0cf18ef23705bb1af1a3fb6586/lm/CMakeLists.txt#L26)):*
> ```CMake
> add_subdirectory(adapter-types)
> 
> if(${CMAKE_SYSTEM_NAME} STREQUAL "Linux")
> ```

so sad :(

---

*[lm/fmtgp/Ch04.hpp, line 1 at r4](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/70#-L3wosvXMBuJ2o2nx0oM:-L3wosvYJcVeDbiEocc0:b-q3t4m8) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/9b1f01ae4a8e23ee4e5d70dcedc890ff956722a4/lm/fmtgp/Ch04.hpp#L1)):*
> ```cpp
> #pragma once
> ```

Why did you change pragma once to include guards? Do you know some advantages to use include guard over pragma once? For my information the both have some +/-. 
In many header only library I have seen the both in the same time are used.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/70)*

**Comment by lukasz-m-maciejewski** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[lm/CMakeLists.txt, line 26 at r4](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/70#-L3x2eERt3Ng2_PEGl0N:-L3xb-m56gCsqVhbfqKY:bh7ppbp) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/1202bf4671a3bb0cf18ef23705bb1af1a3fb6586/lm/CMakeLists.txt#L26)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary><blockquote>

so sad :(
</blockquote></details>

looking for a flame war? :P windows is sad :]

When I have limited time to do something I really don't want to waste it on making something work on a platform that is unusable for development anyway. The amount of time you have to spend to make event a toy C++ project run on a single platform is already huge when compared to something like Python. Time is the most valuable resource you have - once you spend it, you'll never get it back. So it's not actually sad - it's me being strategic about my time investments. ;-)

---

*[lm/fmtgp/Ch04.hpp, line 1 at r4](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/70#-L3wosvXMBuJ2o2nx0oM:-L3xbPfaj3SS4K8YRGIe:b5g8hma) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/9b1f01ae4a8e23ee4e5d70dcedc890ff956722a4/lm/fmtgp/Ch04.hpp#L1)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary><blockquote>

Why did you change pragma once to include guards? Do you know some advantages to use include guard over pragma once? For my information the both have some +/-. 
In many header only library I have seen the both in the same time are used.
</blockquote></details>

I thing we had this discusion about a year ago already. ;-) Personally I don't mind either way. I have a slight preference towards '#pragma once', because it takes less typing But in the end IDEs (or Emacs at least) for some reason complain about pragma once and do not complain about the traditional compile guards. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/70)*

**Comment by Abergard** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[lm/CMakeLists.txt, line 26 at r4](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/70#-L3x2eERt3Ng2_PEGl0N:-L3yEH7zBhONqsQqzZUM:b-2hpbvh) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/1202bf4671a3bb0cf18ef23705bb1af1a3fb6586/lm/CMakeLists.txt#L26)):*
<details><summary><i>Previously, lukasz-m-maciejewski (Łukasz Maciejewski) wrote…</i></summary><blockquote>

looking for a flame war? :P windows is sad :]

When I have limited time to do something I really don't want to waste it on making something work on a platform that is unusable for development anyway. The amount of time you have to spend to make event a toy C++ project run on a single platform is already huge when compared to something like Python. Time is the most valuable resource you have - once you spend it, you'll never get it back. So it's not actually sad - it's me being strategic about my time investments. ;-)
</blockquote></details>

It's not the point (I do not like flaming). Windows is sad, you said. That's why I am using him. To change a world where Window will be happy :)

My mistake I didn't write explicit what I thought. 
You said that even preparing c++ project to work on one platform consume huge number of time.
The said is the fact that sometimes due to lack of somethings (in your situation is times) we need to give up. C++ is a crossplatform language however we still need to pay attention to a few functionality in specific platform.

---

*[lm/fmtgp/Ch04.hpp, line 1 at r4](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/70#-L3wosvXMBuJ2o2nx0oM:-L3yG4HHMjTmgOLsQqHM:b4o2rc0) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/9b1f01ae4a8e23ee4e5d70dcedc890ff956722a4/lm/fmtgp/Ch04.hpp#L1)):*
<details><summary><i>Previously, lukasz-m-maciejewski (Łukasz Maciejewski) wrote…</i></summary><blockquote>

I thing we had this discusion about a year ago already. ;-) Personally I don't mind either way. I have a slight preference towards '#pragma once', because it takes less typing But in the end IDEs (or Emacs at least) for some reason complain about pragma once and do not complain about the traditional compile guards. 
</blockquote></details>

I have to admit, I barely remember it.
Writing this question I was wondering why suddenly have you changed pragma to include guard, did you have a good reason or not. Now I know. It was strongly connected with with your IDEs, nothing special. :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/70)*

**Comment by Abergard** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/70)*

**Pull request merged**
