### PR TITLE
dprog ch290

### PR DESCRIPTION
**Pull request by lukasz-m-maciejewski**
This change is [Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/papuc_exercises/28)

### CODE REVIEW

**Comment by Abergard** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[lm/.clang-format, line 78 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/28#-KW_EbqL-cNPAQcbB3o0:-KW_EbqQK5EslC2kR0SQ:b-lxfjs9) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/c4ff9a6be3271a19860476e036c949163bcd7844/lm/.clang-format#L78)):*
> ```YAML
> UseTab:          Never
> ...
> ```

Shouldn't we had only one .clang-format for our projects?

---

*[lm/dprog/ch290/Instruction.hpp, line 3 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/28#-KW_FYDELhxAb2J7AufA:-KW_FYDELhxAb2J7AufB:b-2wgj32) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/c4ff9a6be3271a19860476e036c949163bcd7844/lm/dprog/ch290/Instruction.hpp#L3)):*
> ```cpp
> #pragma once
> 
> using u8_t = unsigned char;
> ```

Why didn't you use std::uint8_t instead of creating own aliases for unsigned char ?

---

*[lm/dprog/ch290/InstructionLexer.cpp, line 14 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/28#-KW_GcfY0QHx_HMGbXe4:-KW_GcfZPwoEOgJMfhuB:bkuzh65) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/c4ff9a6be3271a19860476e036c949163bcd7844/lm/dprog/ch290/InstructionLexer.cpp#L14)):*
>  if (m.size() != 3)
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>
>     {
>         for (auto i = 0u; i < m.size(); ++i)
>         {
>             std::cout << "m[" << i << "]=" << m[i] << '\n';
>         }
>         throw std::logic_error("epic fail");
</details>

It would be more readable if you extracted it to function/assertion

---

*[lm/dprog/ch290/InstructionLexer.cpp, line 21 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/28#-KW_HQp7IkXfIBSFh1gj:-KW_HQp7IkXfIBSFh1gk:b-zfzqah) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/c4ff9a6be3271a19860476e036c949163bcd7844/lm/dprog/ch290/InstructionLexer.cpp#L21)):*
> if ((registryName.size() == 1 and registryName[0] == 'a'))
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>
>     {
>         reg = Register::reg_a;
>     }
>     else
>     {
>         throw std::logic_error("addressing unknown register");
</details>

This part of code imho should be also extracted to e.g.
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>
>     void myAssert(const bool is, const std::string& message)
>     {
>     if(is == false) throw std::logic_error(message);
>     }
</details>

Your code may now looks like that:
>     myAssert((registryName.size() == 1 and registryName[0] == 'a'),
>                      "addressing unknown register");)'
 >     reg = Register::reg_a;

Doesn't look much cleaner and more elegant?

---

*[lm/dprog/ch290/InstructionLexer.cpp, line 32 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/28#-KW_JTybsvEvKZ1Yi9Gk:-KW_JTyc9L1np4kUXYTE:bnj7hl0) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/c4ff9a6be3271a19860476e036c949163bcd7844/lm/dprog/ch290/InstructionLexer.cpp#L32)):*
> ```cpp
>     int value = std::stoi(valueStr);
> 
>     if (not(value >= std::numeric_limits<u8_t>::lowest() and
> ```

same as above

---

*[lm/dprog/ch290/InstructionLexer.cpp, line 44 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/28#-KW_JWM_7zNRIfU49rEw:-KW_JWM_7zNRIfU49rEx:bnj7hl0) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/c4ff9a6be3271a19860476e036c949163bcd7844/lm/dprog/ch290/InstructionLexer.cpp#L44)):*
> ```cpp
> Instruction buildOutputInstruction(const std::smatch& m)
> {
>     if (m.size() != 3)
> ```

same as above

---

*[lm/dprog/ch290/InstructionLexer.cpp, line 102 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/28#-KW_K4apUc8G0Nn_ZdYH:-KW_K4apUc8G0Nn_ZdYI:bofjtug) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/c4ff9a6be3271a19860476e036c949163bcd7844/lm/dprog/ch290/InstructionLexer.cpp#L102)):*
> ```cpp
> {
>     std::smatch m;
>     for (const auto& pbRel : knownInstructions)
> ```

It looks like find_if...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/28)*

**Comment by Feldmarszalekduda** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/28#-:-KWdCScjh9Dq-2Efm4iI:bnfp4nl)*

**Comment by Abergard** [comment]
Reviewed 24 of 27 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[lm/dprog/ch290/InstructionBuilderCombinator.cpp, line 30 at r2](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/28#-KWtoOsNAZ_2-ePrJQ8q:-KWtoOsNAZ_2-ePrJQ8r:b8sciny) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/589da32bb0209488c6630678af9ed367e6fc56c6/lm/dprog/ch290/InstructionBuilderCombinator.cpp#L30)):*
> ```cpp
> }
> 
> class InstructionBuilderCombinator::Worker
> ```

Why did you write so ugly code ?
Class declaration in cpp file? Why didn't you write it separately and include it here?

---

*[lm/dprog/ch290/LoadInstructionBuilder.cpp, line 17 at r2](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/28#-KWtqIPf16W8nB0g9R55:-KWtqIPgU1ZTxRvCRQ2E:b-2t3ttn) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/589da32bb0209488c6630678af9ed367e6fc56c6/lm/dprog/ch290/LoadInstructionBuilder.cpp#L17)):*
> ```cpp
> LoadInstructionBuilder::buildInstruction(const std::smatch& m) const
> {
>     throw_assert(m.size() == 3, "m contains: " << [](const std::smatch& m) {
> ```

You can extract this lambda to function, btw is it the same code as your smatch_print ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/28)*

**Comment by lukasz-m-maciejewski** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[lm/.clang-format, line 78 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/28#-KW_EbqL-cNPAQcbB3o0:-KWwLQriJeOOgkp6b-Zb:b-gr3zkw) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/c4ff9a6be3271a19860476e036c949163bcd7844/lm/.clang-format#L78)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary>
> Shouldn't we had only one .clang-format for our projects?
</details>
I require very short line length to be able to work comfortably, but I don't want to impose this on everyone. Common clang-format config can serve as a baseline, but sometimes there is a need for customization.

---

*[lm/dprog/ch290/Instruction.hpp, line 3 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/28#-KW_FYDELhxAb2J7AufA:-KWwMBUAdz-l8jlhQ3fA:b5r5xal) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/c4ff9a6be3271a19860476e036c949163bcd7844/lm/dprog/ch290/Instruction.hpp#L3)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary>
> Why didn't you use std::uint8_t instead of creating own aliases for unsigned char ?
</details>
I use this type very often and need the name to be shorter.

---

*[lm/dprog/ch290/InstructionBuilderCombinator.cpp, line 30 at r2](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/28#-KWtoOsNAZ_2-ePrJQ8q:-KWwMNhAUhmHTPSFrN-c:b-2djg4p) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/589da32bb0209488c6630678af9ed367e6fc56c6/lm/dprog/ch290/InstructionBuilderCombinator.cpp#L30)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary>
> Why did you write so ugly code ?
> Class declaration in cpp file? Why didn't you write it separately and include it here?
</details>
"Ugly" is personal opinion - I find this code very pretty. Encapsulating temporary structures needed by the "process" method helps to make explicit what is the lifetime of those structures and allows the helper methods required by the processing to work on common context without creating such temporary structures in the outer class and maintaining them any longer then they are required. Moreover having private implementation class helps to encapsulate run-time dependencies that are internal to the class and not part of the interface. This creates cleaner headers that pull no internal dependencies to the client code. The solution I used here is similar to the pointer-to-implementation idiom - a well established C++ technique - but adjusted to the use-case I have here. 

The Worker class could have been extracted as a completely independent one, but as it has no meaning outside it's outer class, I wanted to make this dependency explicit.

---

*[lm/dprog/ch290/LoadInstructionBuilder.cpp, line 17 at r2](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/28#-KWtqIPf16W8nB0g9R55:-KWwOilE6_sJ4QdU3UDX:b1sndbr) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/589da32bb0209488c6630678af9ed367e6fc56c6/lm/dprog/ch290/LoadInstructionBuilder.cpp#L17)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary>
> You can extract this lambda to function, btw is it the same code as your smatch_print ?
</details>
This is smatch_print, I missed this one when I extracted the method - thanks for pointing this out. :-)

---

*[lm/dprog/ch290/InstructionLexer.cpp, line 14 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/28#-KW_GcfY0QHx_HMGbXe4:-KWwP60uRqjI3iCjGmVP:b-896fix) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/c4ff9a6be3271a19860476e036c949163bcd7844/lm/dprog/ch290/InstructionLexer.cpp#L14)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary>
> >  if (m.size() != 3)
> >     {
> >         for (auto i = 0u; i < m.size(); ++i)
> >         {
> >             std::cout << "m[" << i << "]=" << m[i] << '\n';
> >         }
> >         throw std::logic_error("epic fail");
> 
> It would be more readable if you extracted it to function/assertion
> 
</details>
Done.

---

*[lm/dprog/ch290/InstructionLexer.cpp, line 21 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/28#-KW_HQp7IkXfIBSFh1gj:-KWwP7VSRVg3S-GS-0fW:b-896fix) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/c4ff9a6be3271a19860476e036c949163bcd7844/lm/dprog/ch290/InstructionLexer.cpp#L21)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary>
> > if ((registryName.size() == 1 and registryName[0] == 'a'))
> >     {
> >         reg = Register::reg_a;
> >     }
> >     else
> >     {
> >         throw std::logic_error("addressing unknown register");
> 
> This part of code imho should be also extracted to e.g.
> >     void myAssert(const bool is, const std::string& message)
> >     {
> >     if(is == false) throw std::logic_error(message);
> >     }
> 
> Your code may now looks like that:
> >     myAssert((registryName.size() == 1 and registryName[0] == 'a'),
> >                      "addressing unknown register");)'
>  >     reg = Register::reg_a;
> 
> Doesn't look much cleaner and more elegant?
</details>
Done.

---

*[lm/dprog/ch290/InstructionLexer.cpp, line 32 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/28#-KW_JTybsvEvKZ1Yi9Gk:-KWwP8V5YtaU0jpjQ47K:b-896fix) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/c4ff9a6be3271a19860476e036c949163bcd7844/lm/dprog/ch290/InstructionLexer.cpp#L32)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary>
> same as above
</details>
Done.

---

*[lm/dprog/ch290/InstructionLexer.cpp, line 44 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/28#-KW_JWM_7zNRIfU49rEw:-KWwP90RHRpcS0TTO0QJ:b-896fix) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/c4ff9a6be3271a19860476e036c949163bcd7844/lm/dprog/ch290/InstructionLexer.cpp#L44)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary>
> same as above
</details>
Done.

---

*[lm/dprog/ch290/InstructionLexer.cpp, line 102 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/28#-KW_K4apUc8G0Nn_ZdYH:-KWwP9u2ICeSVOLvImMM:b-896fix) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/c4ff9a6be3271a19860476e036c949163bcd7844/lm/dprog/ch290/InstructionLexer.cpp#L102)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary>
> It looks like find_if...
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/28)*

**Comment by Abergard** [comment]
Reviewed 1 of 29 files at r2, 22 of 22 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[lm/dprog/ch290/InstructionBuilderCombinator.cpp, line 30 at r2](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/28#-KWtoOsNAZ_2-ePrJQ8q:-KWweIw2_zB1xZmrRmUP:bb8ezzx) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/589da32bb0209488c6630678af9ed367e6fc56c6/lm/dprog/ch290/InstructionBuilderCombinator.cpp#L30)):*
I have expressed in a wrong way. I like pimpl-idiom, and I didn't mean to that having declaration of class in private is evil.
By "Ugly" I mean: hard to understand and to review by people other than you. Having too much in one file in my opinion is a bad style. You can extract Worker class to another file and with preprocessor help have things (in my opinion again) clearer.

I will write simple example here to have sure that you understand me.

>    //InstructionBuilderCombinator.hpp file
>    class InstructionBuilderCombinator
>    {
>    public:
>       InstructionBuilderCombinator();
>    private:
>        class Worker;
>    };
>    
>    //InstructionBuilderCombinator.cpp file
>    #include "InstructionBuilderCombinator.hpp"
>    InstructionBuilderCombinator::InstructionBuilderCombinator()
>    {
>        Worker w.
>        w.doSth();
>    }
>    
>    //Worker.hpp
>    #include "InstructionBuilderCombinator.hpp"
>    
>    class InstructionBuilderCombinator::Worker
>    {
>    public:
>    void doSth();
>    };
>    
>    //Worker.cpp
>    #include "Worker.hpp"
>    
>    void InstructionBuilderCombinator::Worker doSth()
>    {
>    ...
>    }

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/28)*

**Comment by lukasz-m-maciejewski** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[lm/dprog/ch290/InstructionBuilderCombinator.cpp, line 30 at r2](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/28#-KWtoOsNAZ_2-ePrJQ8q:-KWwqUECTf6eIv9Bhw2w:bj0t8gs) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/589da32bb0209488c6630678af9ed367e6fc56c6/lm/dprog/ch290/InstructionBuilderCombinator.cpp#L30)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary>
> I have expressed in a wrong way. I like pimpl-idiom, and I didn't mean to that having declaration of class in private is evil.
> By "Ugly" I mean: hard to understand and to review by people other than you. Having too much in one file in my opinion is a bad style. You can extract Worker class to another file and with preprocessor help have things (in my opinion again) clearer.
> 
> I will write simple example here to have sure that you understand me.
> 
> >    //InstructionBuilderCombinator.hpp file
> >    class InstructionBuilderCombinator
> >    {
> >    public:
> >       InstructionBuilderCombinator();
> >    private:
> >        class Worker;
> >    };
> >    
> >    //InstructionBuilderCombinator.cpp file
> >    #include "InstructionBuilderCombinator.hpp"
> >    InstructionBuilderCombinator::InstructionBuilderCombinator()
> >    {
> >        Worker w.
> >        w.doSth();
> >    }
> >    
> >    //Worker.hpp
> >    #include "InstructionBuilderCombinator.hpp"
> >    
> >    class InstructionBuilderCombinator::Worker
> >    {
> >    public:
> >    void doSth();
> >    };
> >    
> >    //Worker.cpp
> >    #include "Worker.hpp"
> >    
> >    void InstructionBuilderCombinator::Worker doSth()
> >    {
> >    ...
> >    }
</details>
You have a point here, but I'm not completely sold on this. Having short files does not seem to be as important for readability as having short methods. 

As to having class definition in the cpp file - when by design the class is not to be used outside that cpp file, I still don't see the need to extract it to a separate header. I need to think it over some more. ;-)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/28)*

**Comment by Abergard** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[lm/dprog/ch290/InstructionBuilderCombinator.cpp, line 30 at r2](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/28#-KWtoOsNAZ_2-ePrJQ8q:-KWyfPGtLsy0WXudo9gR:bnu8cz7) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/589da32bb0209488c6630678af9ed367e6fc56c6/lm/dprog/ch290/InstructionBuilderCombinator.cpp#L30)):*
<details><summary><i>Previously, lukasz-m-maciejewski (Łukasz Maciejewski) wrote…</i></summary>
> You have a point here, but I'm not completely sold on this. Having short files does not seem to be as important for readability as having short methods. 
> 
> As to having class definition in the cpp file - when by design the class is not to be used outside that cpp file, I still don't see the need to extract it to a separate header. I need to think it over some more. ;-)
</details>
I have just wanted to know why did you choose that design :)
I have only one reason to choose implementation out of the same cpp.
If the logic of "Worker" class will be more complicated it will be easier to test it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/28)*

**Comment by lukasz-m-maciejewski** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[lm/dprog/ch290/InstructionBuilderCombinator.cpp, line 30 at r2](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/28#-KWtoOsNAZ_2-ePrJQ8q:-KWyvemzv0cjQIftEGCh:bis211s) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/589da32bb0209488c6630678af9ed367e6fc56c6/lm/dprog/ch290/InstructionBuilderCombinator.cpp#L30)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary>
> I have just wanted to know why did you choose that design :)
> I have only one reason to choose implementation out of the same cpp.
> If the logic of "Worker" class will be more complicated it will be easier to test it.
> 
</details>
Testing is, I think, the strongest argument to extract this class as a separate entity and inject it - or a factory for it (which leads to Law of Demeter violation) and test it separately with mock InstructionBuilder. But the cost (in terms of work required) seems relatively high in this context and I'm doubtful if it's worth it for a toy project such as this - on the other hand is one of the points of the exercise. But I'm somewhat unhappy with having the sort of "module test" that this design led to. It get's the job done, however, so it's not all bad. ;-)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/28)*

**Pull request merged**
