### PR TITLE
Challenge260 td

### PR DESCRIPTION
**Pull request by kn65op**
Part 1

---
This change is [Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/papuc_exercises/32)

### CODE REVIEW

**Comment by lukasz-m-maciejewski** [comment]
please, consider running clang-format to make to code more readable

---

Reviewed 4 of 16 files at r1.
Review status: 4 of 16 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/32#-:-KX2NTQzT9t2I45Tpayb:b-h1jrmw)*

**Comment by Abergard** [comment]
Reviewed 2 of 16 files at r1, 3 of 14 files at r2.
Review status: 5 of 17 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[td/test/test.cpp, line 6 at r2](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/32#-KX2Xg91H50I03uZie4E:-KX2Xg92UNLI2jKXYaLP:b1zkfyh) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/50e22a71ccf379b3be19a58f056450e436ee350d/td/test/test.cpp#L6)):*
> ```cpp
> {
>     std::cout << "123\n";
>     return 0;
> ```

"return 0" in main function is unnecessary. Modern compilator will add it as default.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/32)*

**Comment by kn65op** [comment]
Review status: 5 of 17 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[td/test/test.cpp, line 6 at r2](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/32#-KX2Xg91H50I03uZie4E:-KX2hGPSe3-VzyPR_v-N:b-wlbxzv) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/50e22a71ccf379b3be19a58f056450e436ee350d/td/test/test.cpp#L6)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary>
> "return 0" in main function is unnecessary. Modern compilator will add it as default.
</details>
Yes and no, depends if you want to be explicit or not.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/32)*

**Comment by kn65op** [comment]
Was run

---

Review status: 5 of 17 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/32#-:-KX2hVx3I51R5JMqFrLJ:balyk9b)*

**Comment by lukasz-m-maciejewski** [comment]
Reviewed 3 of 16 files at r1, 11 of 14 files at r2.
Review status: 12 of 17 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[td/challenge260/InstructionLexer.cpp, line 49 at r2](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/32#-KX2Q0waEAASqAJ9Cos9:-KX2Q0waEAASqAJ9CosA:bgfv5y1) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/50e22a71ccf379b3be19a58f056450e436ee350d/td/challenge260/InstructionLexer.cpp#L49)):*
> ```cpp
>         return std::stoi(text);
>     }
>     catch (const std::exception&)
> ```

BTW In an app where stability is not of utmost importance, it'd probably be much better to fail fast and loud. By catching this exception, you hide the error and probably make debugging somewhat harder.

---

*[td/challenge260/InstructionLexer.hpp, line 23 at r2](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/32#-KX2R-FF_2CH2oxlOFc0:-KX2R-FF_2CH2oxlOFc1:b-3nmark) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/50e22a71ccf379b3be19a58f056450e436ee350d/td/challenge260/InstructionLexer.hpp#L23)):*
> ```cpp
>     Tokens parseInstruction(const std::string&);
>     Tokens parseLine(const std::string&);
>     std::string trimWhitespacesOnFront(const std::string& instruction);
> ```

BTW maybe you could try [this](http://www.boost.org/doc/libs/1_60_0/doc/html/string_algo/reference.html#header.boost.algorithm.string.trim_hpp)...

---

*[td/challenge260/LedController.cpp, line 35 at r2](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/32#-KX2RiGpNJO7eS3cV4pu:-KX2RiGpNJO7eS3cV4pv:bvhprpb) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/50e22a71ccf379b3be19a58f056450e436ee350d/td/challenge260/LedController.cpp#L35)):*
> ```cpp
>     stream << bitValue;
>     auto text = stream.str();
>     std::transform(text.cbegin(), text.cend(), text.begin(),
> ```

You can print bitset with [to_string](http://en.cppreference.com/w/cpp/utility/bitset/to_string) method, which accepts as arguments the chars you want for displaying the bits.

---

*[td/challenge260/main.cpp, line 16 at r2](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/32#-KX2T8f6a10A26zqosyo:-KX2T8f7bj0fH9Xed5el:b5e2av1) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/50e22a71ccf379b3be19a58f056450e436ee350d/td/challenge260/main.cpp#L16)):*
> ```cpp
>     while (std::getline(std::cin, input))
>     {
>         const auto tokens = lexer.parseInstructions(input);
> ```

BTW I'm not sure if I'm not seeing something wrong here, but doesn't 'parseInstruction' expect to parse entire input, not a single line?

---

*[td/test/test.cpp, line 6 at r2](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/32#-KX2Xg91H50I03uZie4E:-KX5OX2wMi7OWW_W_ZGR:bqg2yxf) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/50e22a71ccf379b3be19a58f056450e436ee350d/td/test/test.cpp#L6)):*
<details><summary><i>Previously, kn65op (Tomasz Drzewiecki) wrote…</i></summary>
> Yes and no, depends if you want to be explicit or not.
</details>
LGMT - I think we should not focus on details of personal style ;-)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/32)*

**Comment by lukasz-m-maciejewski** [comment]
Reviewed 1 of 16 files at r1.
Review status: 13 of 17 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/32)*

**Comment by lukasz-m-maciejewski** [comment]
Reviewed 1 of 14 files at r2, 1 of 2 files at r3.
Review status: 15 of 17 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/32)*

**Comment by lukasz-m-maciejewski** [comment]
Reviewed 1 of 14 files at r2, 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/32)*

**Comment by kn65op** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[td/challenge260/InstructionLexer.hpp, line 23 at r2](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/32#-KX2R-FF_2CH2oxlOFc0:-KX74UinP5lrQ6YlZ9e5:b-896fix) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/50e22a71ccf379b3be19a58f056450e436ee350d/td/challenge260/InstructionLexer.hpp#L23)):*
<details><summary><i>Previously, lukasz-m-maciejewski (Łukasz Maciejewski) wrote…</i></summary>
> BTW maybe you could try [this](http://www.boost.org/doc/libs/1_60_0/doc/html/string_algo/reference.html#header.boost.algorithm.string.trim_hpp)...
</details>
Done.

---

*[td/challenge260/LedController.cpp, line 35 at r2](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/32#-KX2RiGpNJO7eS3cV4pu:-KX74NuLjQcc1SRcmmRi:b3hsdc0) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/50e22a71ccf379b3be19a58f056450e436ee350d/td/challenge260/LedController.cpp#L35)):*
<details><summary><i>Previously, lukasz-m-maciejewski (Łukasz Maciejewski) wrote…</i></summary>
> You can print bitset with [to_string](http://en.cppreference.com/w/cpp/utility/bitset/to_string) method, which accepts as arguments the chars you want for displaying the bits.
</details>
Already done in next changes

---

*[td/challenge260/main.cpp, line 16 at r2](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/32#-KX2T8f6a10A26zqosyo:-KX7qTsZDxlMFUZxL9Gg:b7xt743) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/50e22a71ccf379b3be19a58f056450e436ee350d/td/challenge260/main.cpp#L16)):*
<details><summary><i>Previously, lukasz-m-maciejewski (Łukasz Maciejewski) wrote…</i></summary>
> BTW I'm not sure if I'm not seeing something wrong here, but doesn't 'parseInstruction' expect to parse entire input, not a single line?
</details>
parseInstruction is capable to parse multiple instructions, however this functionality was not used in final solution

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/32)*

**Comment by kn65op** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[td/challenge260/InstructionLexer.cpp, line 49 at r2](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/32#-KX2Q0waEAASqAJ9Cos9:-KX7rDGf9ZLHeJwweQb8:b-896fix) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/50e22a71ccf379b3be19a58f056450e436ee350d/td/challenge260/InstructionLexer.cpp#L49)):*
<details><summary><i>Previously, lukasz-m-maciejewski (Łukasz Maciejewski) wrote…</i></summary>
> BTW In an app where stability is not of utmost importance, it'd probably be much better to fail fast and loud. By catching this exception, you hide the error and probably make debugging somewhat harder.
</details>
Done.

---

*[td/test/test.cpp, line 6 at r2](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/32#-KX2Xg91H50I03uZie4E:-KX7rG7QB1tPa4Izb26h:b-896fix) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/50e22a71ccf379b3be19a58f056450e436ee350d/td/test/test.cpp#L6)):*
<details><summary><i>Previously, lukasz-m-maciejewski (Łukasz Maciejewski) wrote…</i></summary>
> LGMT - I think we should not focus on details of personal style ;-)
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/32)*

**Comment by Abergard** [comment]
Reviewed 1 of 14 files at r2, 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/32)*

**Comment by lukasz-m-maciejewski** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/32#-:-KX9pYJSf4PhQnhPExhI:bnfp4nl)*

**Comment by lukasz-m-maciejewski** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/32)*

**Comment by lukasz-m-maciejewski** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/32#-:-KXCFu8rrWVh95D-15HN:bnfp4nl)*

**Pull request merged**
