### PR TITLE
Excercise 05 + UT for it

### PR DESCRIPTION
**Pull request by Feldmarszalekduda**
This change is [Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/papuc_exercises/6)

### CODE REVIEW

**Comment by lukasz-m-maciejewski** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[ch04/mb/NGR_04_02_01.hpp, line 6 \[r1\]](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/6#-KLIRTHt6mEksZyq_lKb:-KLIRTHt6mEksZyq_lKc:263549765) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/901592d6e3e7a69975577b95918db944b81f6ef1/ch04/mb/NGR_04_02_01.hpp#L6)):*
> ```cpp
> std::vector<double> collectTemperatures();
> std::string showVector(const std::vector<double>&);
> double getMediana(const std::vector<double>&);
> ```

it's polish or english? either getMediad or policzMediane :P

---

*[ch04/mb/NGR_04_05_01.cpp, line 55 \[r1\]](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/6#-KLISIMCDdSohRNLt6a-:-KLISIMCDdSohRNLt6a0:1194054834) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/901592d6e3e7a69975577b95918db944b81f6ef1/ch04/mb/NGR_04_05_01.cpp#L55)):*
> ```cpp
> bool Calculator::secondIsAlmostZero()
> {
>     const double ReallySmallNumber = 0.00000001;
> ```

consider using consepr - in this context it's more effective

---

*[ch04/mb/NGR_04_05_01.cpp, line 56 \[r1\]](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/6#-KLISDejPYi3aKQft2Le:-KLISDekr0eVuKDYp-ps:-591412577) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/901592d6e3e7a69975577b95918db944b81f6ef1/ch04/mb/NGR_04_05_01.cpp#L56)):*
> ```cpp
> {
>     const double ReallySmallNumber = 0.00000001;
>     if (second < ReallySmallNumber and second > -ReallySmallNumber)
> ```

consider using std::abs http://en.cppreference.com/w/cpp/numeric/math/fabs

---

*[ch04/mb/NGR_04_05_01.cpp, line 112 \[r1\]](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/6#-KLIULYwcp6q2uFxN9_2:-KLIULYwcp6q2uFxN9_3:-1652407638) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/901592d6e3e7a69975577b95918db944b81f6ef1/ch04/mb/NGR_04_05_01.cpp#L112)):*
> ```cpp
>                       << " is equal to " << result;
>             break;
> //        default:
> ```

consider removing the comments

---

*[ch04/mb/NGR_04_05_01.hpp, line 36 \[r1\]](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/6#-KLIWTsEMdN6SDrrPVp4:-KLIWTsF50bRcOoJvnqS:265584765) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/901592d6e3e7a69975577b95918db944b81f6ef1/ch04/mb/NGR_04_05_01.hpp#L36)):*
> ```cpp
>     std::string getResult();
> 
>     FRIEND_TEST(MBB_04_05, throwingErrorAfterGettingEmptyData);
> ```

Well designed class should not declare friendship with test class. You should only need to test public members. In the design you have here, it seems that you need to split the logic part from the UI part.

---

*[ch04/mb/NGR_04_UT.cpp, line 71 \[r1\]](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/6#-KLIXJxY8zhrxSmEDN08:-KLIXJxZ7K6spB8sC9m3:-600381186) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/901592d6e3e7a69975577b95918db944b81f6ef1/ch04/mb/NGR_04_UT.cpp#L71)):*
> ```cpp
> }
> 
> // Excercise 05
> ```

consider removing commented out code

---

*[ch04/mb/NGR_04_UT.cpp, line 221 \[r1\]](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/6#-KLIXmib2fxVPNIGooDs:-KLIXmib2fxVPNIGooDt:-21288722) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/901592d6e3e7a69975577b95918db944b81f6ef1/ch04/mb/NGR_04_UT.cpp#L221)):*
> ```cpp
> }
> 
> //~ TEST(MBB_04_05, tempTest)
> ```

concider removing commented out code

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/6)*

**Comment by Feldmarszalekduda** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[ch04/mb/NGR_04_05_01.cpp, line 112 \[r1\]](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/6#-KLIULYwcp6q2uFxN9_2:-KLNhGpaYfk2k79u5kjm:1293690833) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/901592d6e3e7a69975577b95918db944b81f6ef1/ch04/mb/NGR_04_05_01.cpp#L112)):*
<details><summary><i>Previously, lukasz-m-maciejewski (Łukasz Maciejewski) wrote…</i></summary>
> consider removing the comments
</details>
this section will be uncomment and exception will be throw in case of default

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/6)*

**Comment by lukasz-m-maciejewski** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/6#-:-KM0A2Yo-RKtCDHnDdLH:980077401)*

**Comment by lukasz-m-maciejewski** [comment]
Reviewed 9 of 9 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[ch04/mb/NGR_04_08_01.cpp, line 10 \[r2\]](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/6#-KM0C4Fr02p7Ci0JccT1:-KM0C4FsvG2l3vvJQUlw:1188975934) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/26384bce365c7ff1a7cf300d286cf3283359c10e/ch04/mb/NGR_04_08_01.cpp#L10)):*
> ```cpp
> 	{
> 		std::string error = "Number of grains should be positive!";
> 		throw error;
> ```

consider throwing dedicated exception type

---

*[ch04/mb/NGR_04_08_main.cpp, line 18 \[r2\]](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/6#-KM0CJ677Gy-zCjeFnuT:-KM0CJ677Gy-zCjeFnuU:1794144352) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/26384bce365c7ff1a7cf300d286cf3283359c10e/ch04/mb/NGR_04_08_main.cpp#L18)):*
> ```cpp
> 		          << squares << " pól szachownicy." << std::endl;
> 	}
> 	catch(std::string error)
> ```

consider catching via const ref instead of by value

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/6)*

**Comment by Feldmarszalekduda** [comment]
Review status: 10 of 16 files reviewed at latest revision, 8 unresolved discussions.

---

*[ch04/mb/NGR_04_02_01.hpp, line 6 \[r1\]](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/6#-KLIRTHt6mEksZyq_lKb:-KM0K4qpEcMaInnzekoa:1913357415) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/901592d6e3e7a69975577b95918db944b81f6ef1/ch04/mb/NGR_04_02_01.hpp#L6)):*
<details><summary><i>Previously, lukasz-m-maciejewski (Łukasz Maciejewski) wrote…</i></summary>
> it's polish or english? either getMediad or policzMediane :P
</details>
Corrected to english

---

*[ch04/mb/NGR_04_05_01.hpp, line 36 \[r1\]](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/6#-KLIWTsEMdN6SDrrPVp4:-KM0L6dh5RxSTTbnlFJe:-1494432546) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/901592d6e3e7a69975577b95918db944b81f6ef1/ch04/mb/NGR_04_05_01.hpp#L36)):*
<details><summary><i>Previously, lukasz-m-maciejewski (Łukasz Maciejewski) wrote…</i></summary>
> Well designed class should not declare friendship with test class. You should only need to test public members. In the design you have here, it seems that you need to split the logic part from the UI part.
</details>
That will be reworked, but I need some time to think how to do this well

---

*[ch04/mb/NGR_04_08_01.cpp, line 10 \[r2\]](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/6#-KM0C4Fr02p7Ci0JccT1:-KM0Wj6ICyOc4zKoDbWN:1748221169) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/26384bce365c7ff1a7cf300d286cf3283359c10e/ch04/mb/NGR_04_08_01.cpp#L10)):*
<details><summary><i>Previously, lukasz-m-maciejewski (Łukasz Maciejewski) wrote…</i></summary>
> consider throwing dedicated exception type
</details>
repaired

---

*[ch04/mb/NGR_04_08_main.cpp, line 18 \[r2\]](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/6#-KM0CJ677Gy-zCjeFnuT:-KM0KRjrUG22W2UiVJH2:-82894076) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/26384bce365c7ff1a7cf300d286cf3283359c10e/ch04/mb/NGR_04_08_main.cpp#L18)):*
<details><summary><i>Previously, lukasz-m-maciejewski (Łukasz Maciejewski) wrote…</i></summary>
> consider catching via const ref instead of by value
</details>
Corrected

---

*[ch04/mb/NGR_04_UT.cpp, line 71 \[r1\]](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/6#-KLIXJxY8zhrxSmEDN08:-KM0L1NUneXd-rFewVDE:610327451) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/901592d6e3e7a69975577b95918db944b81f6ef1/ch04/mb/NGR_04_UT.cpp#L71)):*
<details><summary><i>Previously, lukasz-m-maciejewski (Łukasz Maciejewski) wrote…</i></summary>
> consider removing commented out code
</details>
Removed

---

*[ch04/mb/NGR_04_UT.cpp, line 221 \[r1\]](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/6#-KLIXmib2fxVPNIGooDs:-KM0L3YBbFrMJ5WN6SvN:610327451) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/901592d6e3e7a69975577b95918db944b81f6ef1/ch04/mb/NGR_04_UT.cpp#L221)):*
<details><summary><i>Previously, lukasz-m-maciejewski (Łukasz Maciejewski) wrote…</i></summary>
> concider removing commented out code
</details>
Removed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/6)*

**Comment by lukasz-m-maciejewski** [comment]
Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/6)*

**Pull request merged**
