### PR TITLE
[Common] creating common headers folder

### PR DESCRIPTION
**Pull request by lukasz-m-maciejewski**
this is just not the final form, but just a trial

---
This change is [Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/papuc_exercises/35)

### CODE REVIEW

**Comment by kn65op** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/35)*

**Comment by Abergard** [comment]
It would be nice to have namespace for common includes

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/35#-:-KXQRbyxcPptS0ZMbWGe:b-tdsafk)*

**Comment by kn65op** [comment]
Reviewed 1 of 4 files at r1, 1 of 3 files at r2, 9 of 9 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/35)*

**Comment by kn65op** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/35#-:-KXlX-5Y0lVPiRLic6KW:bg7igk9)*

**Pull request merged**
