### PR TITLE
sfml example 01

### PR DESCRIPTION
**Pull request by lukasz-m-maciejewski**
* continuous movement
* semi-functional collision detection for spherical obstacles

---
This change is [Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/papuc_exercises/37)

### CODE REVIEW

**Comment by Abergard** [comment]
Reviewed 9 of 11 files at r1.
Review status: 9 of 11 files reviewed at latest revision, 5 unresolved discussions.

---

*[common/include/fp_manip.hpp, line 9 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/37#-KY3T2gf1UMVMDnvYrsz:-KY3T2gg7ddIEEF9kA7L:b-vbes6x) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/04d83dc6e06329a9b521c04352de3eff508a8ded/common/include/fp_manip.hpp#L9)):*
> ```cpp
> {
> template <typename _Fp>
> bool equal(_Fp a, _Fp b)
> ```

Take into consideration adding universal reference.

---

*[common/include/fp_manip.hpp, line 17 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/37#-KY3TSOYgK9fw3yo7A2f:-KY3TSOZ77a4qOoRCsPB:b-vbes6x) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/04d83dc6e06329a9b521c04352de3eff508a8ded/common/include/fp_manip.hpp#L17)):*
> ```cpp
> 
> template <typename _Fp>
> bool not_equal(_Fp a, _Fp b)
> ```

Take into consideration adding universal reference.

---

*[common/include/fp_manip.hpp, line 21 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/37#-KY3SKped_1VTY2N0GU1:-KY3SKpf9-dFxlUuFNaj:bkk6cpq) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/04d83dc6e06329a9b521c04352de3eff508a8ded/common/include/fp_manip.hpp#L21)):*
> ```cpp
>     static_assert(std::is_floating_point<_Fp>::value,
>                   "fp::not_equal can only be used with floating point types");
>     return std::fabs(a - b) >= std::numeric_limits<_Fp>::epsilon();
> ```

Can we use 'equal' here (E.g. return not equal(std::forward<_Fp>(a), std::forward<_Fp>(b)) ?

---

*[lm/game01/main.cpp, line 53 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/37#-KY3UIuse0JQGAa1IZ7r:-KY3UIutoZo3qGi1-4cp:bffmbgt) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/04d83dc6e06329a9b521c04352de3eff508a8ded/lm/game01/main.cpp#L53)):*
Please consider to implement Game Loop Patterns (Sequencing Pattern)
http://gameprogrammingpatterns.com/game-loop.html

The main loop should look pretty like this:

>  while (true)
>  {
>    processInput();
>    update();
>    render();
>  }

---

*[lm/game01/player.png, line 0 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/37#-KY3monbZ7W_HZALKNi-:-KY3monc08g5aituwZAw:b-e8qj67) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/04d83dc6e06329a9b521c04352de3eff508a8ded/lm/game01/player.png#L0)):*
I hope it is a free asset ;p

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/37)*

**Comment by lukasz-m-maciejewski** [comment]
Review status: 9 of 11 files reviewed at latest revision, 5 unresolved discussions.

---

*[common/include/fp_manip.hpp, line 9 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/37#-KY3T2gf1UMVMDnvYrsz:-KY4e4hNRaUb7S3kpLh-:b-mbq1x0) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/04d83dc6e06329a9b521c04352de3eff508a8ded/common/include/fp_manip.hpp#L9)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary><blockquote>

Take into consideration adding universal reference.
</blockquote></details>

Passing built-in types by reference is [counterproductive](http://stackoverflow.com/a/14013189), since most of them are smaller then the size of a pointer. And this function is expected to handle only those, and uses static assertion to enforce that. 

---

*[common/include/fp_manip.hpp, line 17 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/37#-KY3TSOYgK9fw3yo7A2f:-KY4egbpjgnfZR6FvrEA:b-9chp70) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/04d83dc6e06329a9b521c04352de3eff508a8ded/common/include/fp_manip.hpp#L17)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary><blockquote>

Take into consideration adding universal reference.
</blockquote></details>

as above

---

*[common/include/fp_manip.hpp, line 21 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/37#-KY3SKped_1VTY2N0GU1:-KY4eoZoFA8_cxhtkNzh:bxuk9a0) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/04d83dc6e06329a9b521c04352de3eff508a8ded/common/include/fp_manip.hpp#L21)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary><blockquote>

Can we use 'equal' here (E.g. return not equal(std::forward<_Fp>(a), std::forward<_Fp>(b)) ?
</blockquote></details>

In case the equality condition was any more complicated than this, I'd agree. But in this case I didn't see any benefit in adding additional layer here.

If we had an operator for a class or struct here, then there would be a benefit with such construction, since extending the content of struct would require aligning only a single operator. But in case of floating point comparison I don't expect the equality condition will change any time soon, so having each operator perform it's check directly was, in my opinion, more beneficial

---

*[lm/game01/main.cpp, line 53 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/37#-KY3UIuse0JQGAa1IZ7r:-KY4g2jgNmQnMItgxWoU:b-2noefg) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/04d83dc6e06329a9b521c04352de3eff508a8ded/lm/game01/main.cpp#L53)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary><blockquote>

Please consider to implement Game Loop Patterns (Sequencing Pattern)
http://gameprogrammingpatterns.com/game-loop.html

The main loop should look pretty like this:

>  while (true)
>  {
>    processInput();
>    update();
>    render();
>  }
</blockquote></details>

I'll look into this, but if you squint your eyes just right, it almost does... ;-) 

I don't think I can change the loop termination condition - it's done this way in all SFML examples I've seen. It could probably be changed to 
``` C++
if (not mainWindow.isOpen())
    break;
```
but I'm not sure it would improve anything.

Update and render are done inside the advance method, so it's kinda-sorta like you said... and the of the loop body is all input processing. And yeah, it makes sense to extract it to a separate function, but I was focusing more on exploring various SFML features. I don't intend for this subproject, to be a basis for any further development, only a library exploration.

Anyway, I'll read up on what you posted here. I'm not sure about refactoring this thing here, but I'll definitely use this construct in future, since it seems to make a lot of sense.

---

*[lm/game01/player.png, line  at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/37#-KY3monbZ7W_HZALKNi-:-KY4iG8s2TDHOiYFIMuA:b-5r5m1h) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/04d83dc6e06329a9b521c04352de3eff508a8ded/lm/game01/player.png#L)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary><blockquote>

I hope it is a free asset ;p
</blockquote></details>

Heh, I hope so too. I found it [here](https://github.com/SFML/SFML/wiki/Source:-AnimatedSprite) and originally wanted to replace the red dot with that animation, but then I focused more on circle collisions, since there was a lot of fun math in there - which I haven't yet solved completely. ;-) 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/37)*

**Comment by Abergard** [comment]
Reviewed 2 of 11 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[lm/game01/main.cpp, line 23 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/37#-KY4xVDarlFqx-X1tlMy:-KY4xVDarlFqx-X1tlMz:b-q5e1tq) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/04d83dc6e06329a9b521c04352de3eff508a8ded/lm/game01/main.cpp#L23)):*
>  while (mainWindow.pollEvent(event))

---

*[lm/game01/main.cpp, line 53 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/37#-KY3UIuse0JQGAa1IZ7r:-KY4x8F27qiYNordkGR0:b-q9v6m1) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/04d83dc6e06329a9b521c04352de3eff508a8ded/lm/game01/main.cpp#L53)):*
Ok. I know that we are learning SFML now. I am not want to persuade you to create pro uber main loop, but only to extract input reading into separate function :)

The while-loop
>   while (mainWindow.pollEvent(event))
is fine and should stay. The "while(true)" was only example to show that I would like to have short and clean loop.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/37)*

**Comment by kn65op** [comment]
Reviewed 1 of 11 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[.gitignore, line 41 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/37#-KY5c-OkWI0chvXJ4G6G:-KY5c-OlN5ErH_fVeoQC:bop1sxl) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/04d83dc6e06329a9b521c04352de3eff508a8ded/.gitignore#L41)):*
> ```
> 
> build/*
> build-*/*
> ```

Shouldn't such entries been in private .gitignore?

---

*[common/include/fp_manip.hpp, line 21 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/37#-KY5cIS7c8SN-4b09nBa:-KY5cIS7c8SN-4b09nBb:bswj2d0) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/04d83dc6e06329a9b521c04352de3eff508a8ded/common/include/fp_manip.hpp#L21)):*
> ```cpp
>     static_assert(std::is_floating_point<_Fp>::value,
>                   "fp::not_equal can only be used with floating point types");
>     return std::fabs(a - b) >= std::numeric_limits<_Fp>::epsilon();
> ```

Why not use euqal?
return !equal(a,b)?

---

*[lm/game01/main.cpp, line 5 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/37#-KY5cqT13M6OHV7PsFX4:-KY5cqT13M6OHV7PsFX5:b-ij88df) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/04d83dc6e06329a9b521c04352de3eff508a8ded/lm/game01/main.cpp#L5)):*
> ```cpp
> #include <iostream>
> 
> int main(int /*argc*/, char** /*argv*/)
> ```

If you don't use arguments you can just write int main()

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/37)*

**Comment by lukasz-m-maciejewski** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[.gitignore, line 41 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/37#-KY5c-OkWI0chvXJ4G6G:-KY5qXZ9YxXwyV5V50Ek:blzjhst) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/04d83dc6e06329a9b521c04352de3eff508a8ded/.gitignore#L41)):*
<details><summary><i>Previously, kn65op (Tomasz Drzewiecki) wrote…</i></summary><blockquote>

Shouldn't such entries been in private .gitignore?
</blockquote></details>

Is it even possible to have private gitignore? Besides, using directory "build" as build dir is pretty much standard practice with cmake - sort of like "usr" or "etc". As to the second entry - "build-*" - I found it useful to have per-branch build dirs, but since the .gitignore file is common, I created a "build-*" ignore rule, not "build-lm-sfml-game01".

---

*[common/include/fp_manip.hpp, line 21 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/37#-KY5cIS7c8SN-4b09nBa:-KY5rCOr6CWSXYygOj1Q:bmxm4mu) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/04d83dc6e06329a9b521c04352de3eff508a8ded/common/include/fp_manip.hpp#L21)):*
<details><summary><i>Previously, kn65op (Tomasz Drzewiecki) wrote…</i></summary><blockquote>

Why not use euqal?
return !equal(a,b)?
</blockquote></details>

I thought I already addressed the issue above.

---

*[lm/game01/main.cpp, line 5 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/37#-KY5cqT13M6OHV7PsFX4:-KY5rQSxuUsdNN8PCrEY:b-w3ewd9) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/04d83dc6e06329a9b521c04352de3eff508a8ded/lm/game01/main.cpp#L5)):*
<details><summary><i>Previously, kn65op (Tomasz Drzewiecki) wrote…</i></summary><blockquote>

If you don't use arguments you can just write int main()
</blockquote></details>

Because this way I have them handy when I need them. Besides I simply prefer this style.

---

*[lm/game01/main.cpp, line 23 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/37#-KY4xVDarlFqx-X1tlMy:-KY5rk_ihDJ-i3aQKgya:b2nh8n9) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/04d83dc6e06329a9b521c04352de3eff508a8ded/lm/game01/main.cpp#L23)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary><blockquote>

>  while (mainWindow.pollEvent(event))
</blockquote></details>

??

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/37)*

**Comment by Abergard** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[lm/game01/main.cpp, line 23 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/37#-KY4xVDarlFqx-X1tlMy:-KY5sFW-Quppkc66ryff:bray8s5) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/04d83dc6e06329a9b521c04352de3eff508a8ded/lm/game01/main.cpp#L23)):*
<details><summary><i>Previously, lukasz-m-maciejewski (Łukasz Maciejewski) wrote…</i></summary><blockquote>

??
</blockquote></details>

Ohh... this comment has been added by mistake sorry :(

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/37)*

**Comment by Feldmarszalekduda** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/37#-:-KYUmVZU4twu4vhRrVEq:bnfp4nl)*

**Comment by lukasz-m-maciejewski** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[.gitignore, line 41 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/37#-KY5c-OkWI0chvXJ4G6G:-KYUmkZszj-AQVJD0Fo7:b-896fix) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/04d83dc6e06329a9b521c04352de3eff508a8ded/.gitignore#L41)):*
<details><summary><i>Previously, lukasz-m-maciejewski (Łukasz Maciejewski) wrote…</i></summary><blockquote>

Is it even possible to have private gitignore? Besides, using directory "build" as build dir is pretty much standard practice with cmake - sort of like "usr" or "etc". As to the second entry - "build-*" - I found it useful to have per-branch build dirs, but since the .gitignore file is common, I created a "build-*" ignore rule, not "build-lm-sfml-game01".
</blockquote></details>

Done.

---

*[common/include/fp_manip.hpp, line 21 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/37#-KY5cIS7c8SN-4b09nBa:-KYUmiVKkg0IBf-6Mz7G:b-896fix) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/04d83dc6e06329a9b521c04352de3eff508a8ded/common/include/fp_manip.hpp#L21)):*
<details><summary><i>Previously, lukasz-m-maciejewski (Łukasz Maciejewski) wrote…</i></summary><blockquote>

I thought I already addressed the issue above.
</blockquote></details>

Done.

---

*[lm/game01/main.cpp, line 5 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/37#-KY5cqT13M6OHV7PsFX4:-KYUmjuOS0fovvmJu1EM:b-896fix) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/04d83dc6e06329a9b521c04352de3eff508a8ded/lm/game01/main.cpp#L5)):*
<details><summary><i>Previously, lukasz-m-maciejewski (Łukasz Maciejewski) wrote…</i></summary><blockquote>

Because this way I have them handy when I need them. Besides I simply prefer this style.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/37)*

**Comment by lukasz-m-maciejewski** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[common/include/fp_manip.hpp, line 21 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/37#-KY5cIS7c8SN-4b09nBa:-KYUmmkusysq7q5S-9j1:b-896fix) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/04d83dc6e06329a9b521c04352de3eff508a8ded/common/include/fp_manip.hpp#L21)):*
<details><summary><i>Previously, lukasz-m-maciejewski (Łukasz Maciejewski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/37)*

**Comment by Abergard** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[.gitignore, line 41 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/37#-KY5c-OkWI0chvXJ4G6G:-KYUnGXKReA_f8T65XVK:b2nhktp) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/04d83dc6e06329a9b521c04352de3eff508a8ded/.gitignore#L41)):*
<details><summary><i>Previously, lukasz-m-maciejewski (Łukasz Maciejewski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

OK.

---

*[common/include/fp_manip.hpp, line 21 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/37#-KY5cIS7c8SN-4b09nBa:-KYUnFfScd_olzBsJadV:b2nhktp) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/04d83dc6e06329a9b521c04352de3eff508a8ded/common/include/fp_manip.hpp#L21)):*
<details><summary><i>Previously, lukasz-m-maciejewski (Łukasz Maciejewski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

OK.

---

*[lm/game01/main.cpp, line 5 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/37#-KY5cqT13M6OHV7PsFX4:-KYUnDUUAieIZEZ6VOqo:bb70vlp) ([raw file](https://github.com/nadzwyczajnagruparobocza/papuc_exercises/blob/04d83dc6e06329a9b521c04352de3eff508a8ded/lm/game01/main.cpp#L5)):*
<details><summary><i>Previously, lukasz-m-maciejewski (Łukasz Maciejewski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

OK.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/papuc_exercises/37)*

**Pull request merged**
